### ISSUE TITLE
Mintty not echo any character user types if an abrupt interruption has happened

### ISSUE THREAD

**Issue by abdulbadii** [mintty/mintty#1013]
Why pretty often doesn't Mintty echo any character user types it after an abrupt interruption has happened either by control-c or ctrl-z.
How to restore this capability by a Linux shell command?

**Comment by mintty** [comment]
For a clear issue description, an actual example would help instead of "pretty often". Anyway, the tty line ("pty") can be set to various modes (check with program `stty`). If you interrupt an application that cannot (or does not, due to careless implementation) restore non-echo or other modes before returning to the shell, you'll get into such a state. Note that this has nothing to do with mintty.
You can restore tty mode with the command `reset`. Mintty offers a reset function in its menu (right-click) or via Alt+F8. However, both Alt+F8 and mouse click could also be reconfigured. Try Shift+right-click then.

**Comment by mintty** [comment]
Closing as this is not a terminal issue.
