### ISSUE TITLE
crossterm (a Rust crate/lib for implementing terminal-based interfaces) not getting any input events from mintty 3.4.3

### ISSUE THREAD

**Issue by DanielKonopka** [mintty/mintty#1070]
To reproduce:

1. Get Rust and Cargo setup.
2. Get crossterm. (https://github.com/crossterm-rs/crossterm)
3. Go into crossterm/examples directory.
4. Run **cargo run --example event-read**

Expected behavior:

event-read getting input events (keyboard, mouse)

Current behavior:

Keyboard events not registered, but echoed, with caret following.
Mouse events not registered, not echoed.

CTRL-C works.

Also, all the keystrokes typed during program execution (that should be registered as key events) after pressing Enter, will form commands that get executed as soon as event-read example terminates.

For example, if you type keystrokes "ccccccc" and hit Enter, a command "ccccccc" is executed by the shell once event-read is terminated forcibly.

**Comment by mintty** [comment]
From a quick glance at the crossterm project page, I only have a vague impression what the purpose of that thing might be. I'd be willing to look further but you cannot expect me to also explore rust or cargo too on this occasion, so a more basic test case would be needed.
However, I do have a suspicion what the problem might be. It could have a specific implementation for the Windows console, as they refer to the Windows conhost. However, conhost has a very specific, not terminal-like API to be used rather than being escape-controlled. So if crossterm expects the terminal to be a conhost because it runs on Windows, that will fail as mintty is not a conhost. Did you build crossterm in the cygwin environment at least?

**Comment by mintty** [comment]
Also, neither crossterm nor rust seem to care to provide clear options to get them set up. For rust, there is no source download available. A Windows installer suggests the incompatibility issues described above.
You could try to use it within WSL as that's mentioned by them. In that case, I would in fact expect crossterm to work inside mintty, from WSL.

**Comment by DanielKonopka** [comment]
@mintty, Thank you for quick response.
I'm not familiar with neither Rust nor crossterm. I've stumbled upon them, because I needed a sed debugger. That's when I found desed (https://github.com/SoptikHa2/desed). It is written in Rust and uses crossterm crate to handle its UI.

I've compiled it all within MSYS2. Do you have it installed by any chance?
It contains Rust package (run MSYS2 in **Mingw64** mode and **pacman -S mingw64/mingw-w64-x86_64-rust 1.48.0-1**).

Once you have it installed, it's a matter of going to: https://github.com/crossterm-rs/crossterm and getting the project files. Then, you go to examples directory and run **cargo run --example event-read**, to compile and run the example.

If you feel like you need further assistance on this, let me know. Also, I can send you the compiled event-read.exe binary, as a last resort.

**Comment by mintty** [comment]
OK, rust is not available as a cygwin package, now we see
pacman -S mingw64/**mingw-w64-x86_64**-rust
where the "mingw" part suggests it's a toolchain living in the Windows domain, not the Posix domain as supported by Cygwin or Mingw64. This supports my suspicion it's a compatibility issue, where either the whole rust environment or the crossterm library decides to run in Windows mode and use the conhost API rather than terminal interaction. As indicated above, that cannot work.
So the way to go (apart from turning to WSL) would be to make a Posix package (i.e. not mingw) of rust in either the cygwin or Mingw64 environment. If you'd like to try that, I'll appreciate your further insights.

**Comment by mintty** [comment]
(Replacing some occurrences of Mingw64 by MSYS2 above, to reflect the proper environment.)

> As indicated above, that cannot work.

Actually, it might even work if the Windows ConPTY API was involved which is now supported by cygwin, but unfortunately disabled by MSYS2 by default. You can enable it with something like MSYS=enable_pcon, if I remember correctly.

**Comment by Biswa96** [comment]
Agreed! we're in ConPTY thing! Enabling ConPTY fixes this issue.

**Comment by DanielKonopka** [comment]
The big issue is... I'm on Windows 7 environment and can't switch to Windows 10...

**Comment by Biswa96** [comment]
In Win7, ConPTY is not available. You could try with [winpty][1] package. Install it using `pacman -S winpty` command. Then `winpty.exe <rest of your command>`.

[1]: https://packages.msys2.org/package/winpty?repo=msys&variant=x86_64

**Comment by DanielKonopka** [comment]
winpty fixes input problem, but then, rendered UI is all out of place, totally corrupted, with misplaced glyphs, etc.

**Comment by Biswa96** [comment]
Last option not to use mintty 🙃 Run this command in cmd `C:\msys64\msys2_shell.cmd -defterm -no-start -mingw64` assume msys2 is installed in `C:\msys64` path.

**Comment by mintty** [comment]
Well, the other last option is to port the toolchain (rust, crossterm, ...) to Posix either in cygwin or MSYS2.

**Comment by DanielKonopka** [comment]
They say picture is worth 1000 words so I've prepared some GIFs to show you what it really looks like... (click on each of these to see unscaled version)

1. mintty - rendering is OK, input is wrong.
![mintty_render_ok_input_bad](https://user-images.githubusercontent.com/28635788/101529066-593a5100-3990-11eb-826f-e6c986a6a748.gif)

2. mintty + winpty - input is OK, rendering is wrong.
![mintty_winpty](https://user-images.githubusercontent.com/28635788/101529328-b8986100-3990-11eb-9a39-8841b3d26084.gif)

3. msys2 under conhost
![conhost_bad](https://user-images.githubusercontent.com/28635788/101529437-d6fe5c80-3990-11eb-8184-b6ee34f10dd8.gif)

**Comment by avih** [comment]
You're trying to run a windows-console program inside mintty - which is not a windows console. There are workarounds like winpty which may or may not handle it correctly, but ultimately you should just run it in a windows console - because that's where it was built to run.

**Comment by DanielKonopka** [comment]
@avih, it was compiled with Rust running under Mingw64. if I run it in plain Windows conhost, it behaves just like on the 3rd GIF. I think I'll take the last chance - with Cygwin and we'll see how it goes.

**Comment by avih** [comment]
mingw is just another way to say plain windows. I.e. not cygwin (and not native msys2). Sounds like it's just broken, and you should report the issues to whoever built/packaged it.

Either way, that's outside the scope of mintty, though of course nothing prevents you from trying worksrounds, but that's exactly what they are.
