### ISSUE TITLE
Feature Request: Update default prompt to use OSC 9;9 allowing to create new tab with same cwd in Windows Terminal

### ISSUE THREAD

**Issue by axcadsd** [mintty/mintty#1106]
Windows Terminal has a feature to create a new tab with the same working directory as the current tab. This is done by wrapping up the path in the prompt with OSC 9;9.

Would it be possible to have this done by default in mintty?
See https://github.com/PowerShell/PowerShell/issues/15469 for a similar issue with more details.

**Comment by mintty** [comment]
Did you close the issue intentionally?
A mechanism to set a working directory in order to be used for this purpose is available. It's OSC 7, however, as previously defined by some other terminals.
A variant of the function to clone a terminal could be provided that also clones the working directory even without OSC 7.

**Comment by mintty** [comment]
Released 3.5.1.
