### ISSUE TITLE
replies to control sequences are out of order

### ISSUE THREAD

**Issue by anntzer** [mintty/mintty#1118]
On mintty 3.5.0 + wsl (shell: /bin/sh, no prompt), requesting XTVERSION and then the Primary DA (`printf '\033[>0q\033[c'`) yields `^[[?1;0c^[P>|mintty 3.5.0^[\`, i.e. the replies are correct, but made out of order.

**Comment by mintty** [comment]
The Primary DA response to ESC[c is also wrong. That's because this response is intercepted by wsl and responded by it, to which mintty has no influence. For transparent invocation of WSL from mintty, use wslbridge2. The wsltty package bundles it with mintty to provide a true WSL terminal experience.

**Comment by mintty** [comment]
This issue may be overcome once a fix of microsoft/terminal#1173 get integrated into Windows.

**Comment by anntzer** [comment]
Thanks for the quick reply and explanation.  It's hard for me to judge whether there's anything to be done on your side, so feel free to close this issue if there isn't.
