### ISSUE TITLE
Scrolling doesnt work?

### ISSUE THREAD

**Issue by kloklojul** [mintty/mintty#1121]
I had an old version of mintty running on my windows 10 machine and everything regarding the scrolling worked fine. Scrolling via scrollbar and via the mouse wheel worked fine. I had to reinstall git with mintty and now scrolling with the mouse wheel generates ^[[B^[[B^[[B and ^[[A^[[A^[[A. The scrollbar also doesnt work. It's there but doesn't have a pullable bar. When i resize the text more of the log is beeing showed so the log is not gone but simply unaccessable.
Anyway i can fix this or is this a know bug? I couldn't find anything regarding this in the issues or in a quick google search.

**Comment by mintty** [comment]
This isn't related to the new version - otherwise lots of people would have complained already. Changing title.
Mouse wheel sending ESC[A/B and scrollbar disabled suggests your terminal session is in Alternate Screen mode, which is normally activated by screen oriented programs like text editors. Type `printf '\e[?47l'` to reset the mode for testing.
Check what your environment does to get the mode activated.

**Comment by kloklojul** [comment]
you are absolutly correct, while porting my old setup i forgot about a script i wrote that took care of this and didn't move it to the new installation. Silly me. Thanks for the help and sorry for the disturbance.

**Comment by Biswa96** [comment]
Just curious how I can reproduce your issue (or should I call it feature).

**Comment by kloklojul** [comment]
> Just curious how I can reproduce your issue (or should I call it feature).

My vps are setup in a way that they open new ssh connections in a new screen. And after I reinstalled windows I forgot that I had a script running that binded the mouse scroll in mintty to behave like it is not inside a screen session. After a while I forgot about it and thought that's the default behavior of mintty
