### ISSUE TITLE
Private mode 80 (DECSDM) is the wrong way around

### ISSUE THREAD

**Issue by j4james** [mintty/mintty#1127]
When `DECSDM` is set, Sixel scrolling should be _disabled_, and when `DECSDM` is reset, Sixel scrolling should be _enabled_ (and this is the default). This behaviour has recently been confirmed on an actual DEC VT340 device.

Now I know Mintty initially implemented this correctly, and then the mode was reversed in commit 914e0a1e306a06075bf90a68d92a9b3a1ee5d5e3 to match XTerm. But XTerm has now corrected its `DECSDM` implementation (see https://github.com/ThomasDickey/xterm-snapshots/commit/b40e561404bf35c180e15ea975139e813d3c45b5). So if you want to match what XTerm is doing, you should probably revert your code to how you had it initially.

**Comment by mintty** [comment]
Thanks for the hint. Now it's a challenge to notify all people that will be affected by that fix...
@saitoha, are you aware of this?

**Comment by j4james** [comment]
I don't think a lot of applications are likely to be using this mode because it's always been broken, given that half the terminals were implementing it one way, and half the other. And I've raised issues or posted comments on the terminals I'm aware of that had it the wrong way around. That includes Contour, Alacritty, and Xterm.js (the latter two are unreleased branches, as far as I'm aware, so not likely to be that widely used).

**Comment by j4james** [comment]
I should add that _lsix_ was using mode 80, but stopped doing so a while ago. And I know _notcurses_ is still using mode 80 for reasons I cannot fathom, but is well aware of the issue and is prepared to add terminal version checks to handle changes in behaviour.

**Comment by avih** [comment]
FWIW, mlterm also supports sixel, but no idea which way DECSDM  goes, if at all.

**Comment by dankamongmen** [comment]
> And I know _notcurses_ is still using mode 80 for reasons I cannot fathom

=]. my reasoning is thus (not to clutter up your issue tracker @mintty):

* unless given reason to believe otherwise, assume terminals to have copied-and-pasted from XTerm source
* XTerm source up until very recent times had the incorrect behavior
* i've grown my little project to the point where people generally let me know about behavioral changes now
* when i encounter new terminals, i find out immediately and trivially which way they roll
* if anyone uses notcurses on a terminal with opposite behavior, it'll be quickly obvious that things are horribly wrong, and i'll hopefully get a bug report

with that said, i wholeheartedly support this change, and am happy to accommodate it!

when my perception of the statistical distribution of terminal origins changes, i will change the default to reflect it.

**Comment by j4james** [comment]
> FWIW, mlterm also supports sixel, but no idea which way DECSDM goes, if at all.

MLTerm has switched its behaviour a couple of times, but is currently implementing `DECSDM` correctly.

**Comment by mintty** [comment]
Released 3.5.2.
