### ISSUE TITLE
Question on Copy/Paste

### ISSUE THREAD

**Issue by cherry933** [mintty/mintty#1138]
I just upgraded to mintty 3.5.2 and got a quick question:  I copied some plain text into windows clipboard , and then pasted it into mintty shell window: 

_echo 111
echo 222
echo 333_

Why I have to press ENTER key to execute them? It use to get executed at once.  Not sure if anything wrong with my configuration. Thanks

**Comment by mintty** [comment]
This is not caused by mintty. This is new behaviour of the shell, intended to prevent copy-and-paste injection attacks.
It can be disabled by this setting in `~/.inputrc`
`set enable-bracketed-paste off`
but mind it's considered a security measure that helps you check malicious clipboard contents before it gets executed.

**Comment by cherry933** [comment]
Thanks a lot!!!  My issue was resolved.  Frequently I need to run scripts/command saved in text files or documents. So bracketed paste mode is very inconvinent for me.
