### ISSUE TITLE
Superscript/subscript - request for information, plus "small text" feature request

### ISSUE THREAD

**Issue by leonerd** [mintty/mintty#1171]
Hi, two things:

Firstly: I'm interested in where you got the idea for SGRs 73/74/75 for superscript/subscript/reset. They don't appear anywhere else that I can find - did you invent them? Either way, I've just added it to libvterm and my big spreadsheet of known terminal sequence codes. I'll likely also add it to libtickit as well, for output purposes.

I'm curious to where the numbering idea comes from - and in particular why it doesn't start at just 70? Are there other plans to put other behaviours in the earlier numbers?

Secondly: The reason I ask is because while implementing it, I found it would be quite easy to also do a "small text" version - render at the same size as the superscript/subscript characters but without the baseline position adjustment, so leave it central with the rest of the text. This would be a nice way to render things like the "SMALL CAPS" ability of nroff and similar.

Perhaps if there's no other plans around the 7x number range, that could be added as 72?

**Comment by leonerd** [comment]
Actually, further thoughts maybe lead to 70/71/72 between them being just baseline up / down, and just small-text in some order; allowing then for 73/74 to be the combinations of those which create superscript / subscript, and finally 75 to reset all of the above.

**Comment by mintty** [comment]
I had the idea for super/sub-script and also shadowed because these attributes are supported by terminfo capabilities. I also got the idea for overstrike from there, although that is not an attribute in terminfo but a feature, and somewhat unclear how it would get involved.
Just up/down is not really feasible as it would overlap into previous/next lines.
Zoomed-down display would not really be what's called small caps in typography. Small caps letters are not just smaller, they are also adjusted in design, to still have original stem widths and thus fit to the main text. Some text processing software commit the sin of offering smaller text under the false label of small caps...

**Comment by j4james** [comment]
> I also got the idea for overstrike from there, although that is not an attribute in terminfo but a feature, and somewhat unclear how it would get involved.

As far as I know, devices that support overstrike don't typically turn that functionality on and off - that's just the way they work all the time. An obvious example would be a simple dot matrix printer. If you print some text, followed by a carriage return, and then some more text, the second lot of text will be printed on top of the first. There's no way for the printer to _not_ do that.

That said, I believe some overstrike terminals had the ability to erase characters by overstriking with a space, and that would provide a way to replace existing characters instead of overstriking them. I think there is a separate terminfo capability to indicate that behavior.

**Comment by mintty** [comment]
I've changed the implementation so that combining the superscript and subscript attributes results in the desired behaviour.
However, I don't plan to assign that a distinct SGR attribute number, or mention it in the attributes list, for the reason above.
Also slightly adjusted the subscript position, and keeping the smallscript position slightly above the baseline, for better distinction from subscript.

**Comment by mintty** [comment]
@j4james, thanks for the background, and one could wonder which other controls would clear output on such a video terminal (probably just clearscreen), but in fact none of the terminals in the current terminfo database has any of the eo,os,ul attributes.
Another story aside: I once worked with a video card that had no other method to move the cursor back or up than cursor home, and I adapted output routines of the WordMaster editor to it.

**Comment by j4james** [comment]
@mintty In case you weren't aware, there are actually "standard" sequences for selecting subscript and subscript. In ECMA-48 there are the `PLD` and `PLU` sequences, although Leonerd would argue that those only support the baseline movement and don't allow for adjusting the size (I disagree). And then DEC also supported additional private SGR sequences for subscript and superscript on several of their printers (`\e[?4m` turns on superscript, `\e?5m` turns on subscript, and `\e?24m` turns them both off - they'd also be reset with `\e[0m` and `\e[?0m`).

**Comment by mintty** [comment]
Thanks again. I think I saw PLD/PLU when I checked out for the feature but decided against using them as their stateful description does not fit into the SGR character attribute model which is more suitable for rendering variations.
I was not aware of DEC private SGRs. Where are those described? If anyone requests, I could add them as SGR aliases but then as you say they were only used for printers.

**Comment by j4james** [comment]
I think this is probably the best reference (see page 7-78):
https://vaxhaven.com/images/f/f7/EK-PPLV2-PM-B01.pdf

**Comment by wez** [comment]
As it happens, I'm adding super/subscript to wezterm at the moment.

My 2 cents on small text are that it feels like that should have a separate SGR code to activate, as it is semantically different from super/subscript and it feels a bit awkward that it is possible to turn on both super and sub at the same time. Of course, you can use the underlying attribute bits how you want, I just think that 73, 74 and 75 should be mutually exclusive in their effect on those attribute bits.

**Comment by j4james** [comment]
@wez Just FYI, if you choose to stick with the 73/74/75 SGR values for this, be aware that you're almost certainly going to be incompatible with VTE (assuming they implement subscript/superscript support at all). The VTE maintainer has made it very clear that they wouldn't support Mintty's proprietary SGR extension, and I think would most likely follow the DEC implementation if anything.

**Comment by wez** [comment]
@j4james Thanks; yeah, I saw your comment about the DEC private codes. I'll look at those: it was easiest to add SGR code to get the ball rolling and test with.

**Comment by mintty** [comment]
Released 3.6.2.

**Comment by mintty** [comment]
This sequence may need to be withdran as it conflicts (#1189) with XTQMODKEYS (xterm 377).

**Comment by mintty** [comment]
To repeat and explicitly address @leonerd for libvterm, the DEC private SGRs will vanish from mintty after only 1 release of existence because they conflict with a new xterm control.

**Comment by wez** [comment]
@mintty are you keeping the 73/74/75 SGR sequences? Curious about how you plan to expose this feature!

**Comment by leonerd** [comment]
Ah this shouldn't worry me too much. libvterm already accepts both sequences, but any of my code that emits them (libtickit or String::Tagged::Terminal) both use the 73/74/75 range anyway and not the DEC private ones. So all should be fine.
Thanks for the headsup though.

**Comment by mintty** [comment]
Released 3.6.3, with DEC private SGRs withdrawn.
