### ISSUE TITLE
Query of ModifyOtherKeys (CSI ? 4 m) causes font size to change to about 4 points

### ISSUE THREAD

**Issue by ghgary** [mintty/mintty#1189]
XTerm version 377 introduced a new control sequence, CSI ? Pp m, Query key modifier options. With Pp = 4, this queries modifyOtherKeys. (See https://invisible-island.net/xterm/ctlseqs/ctlseqs.html.) Earlier versions of XTerm appear to ignore this sequence.

When this sequence is sent to mintty version 3.6.2-1, mintty changes its font size to something very tiny, I'd guess 4 pts. (I have not tested other versions of mintty.)

This is a problem because as of patch 9.0.980, Vim sends this sequence to its controlling terminal to query modifyOtherKeys if it thinks that terminal is an XTerm, e.g., TERM=xterm-256color. Mintty responds by setting a tiny font which is used when the user types an ex command into Vim's command line.

**Comment by j4james** [comment]
FYI, I raised this issue with Thomas on Monday as well as the fact that the new `OSC 60` sequence he introduced conflicts with Contour. I didn't explicitly ask him whether he would revise XTerm to avoid the conflict, and he didn't give me any indication of his intention one way or the other, but it's possible he may still revert those changes if he cares about interoperability with other terminals.

**Comment by mintty** [comment]
I plan to implement the new modifyOtherKeys query but right now it would not do anything in mintty.
Don't how you achieved to minimize the font size but what you describe is not reproducible here.

**Comment by mintty** [comment]
Sorry, my test case was flawed and you are right, the sequence with 4 sets the superscript attribute in 3.6.2. I've contacted @ThomasDickey how to resolve this issue and may have to withdraw the other sequence (#1171).

**Comment by j4james** [comment]
@mintty Did you ever get a reply from Thomas about this? I suggested to him a couple of weeks ago that it might be a better idea to use a standard `DECRQSS` query to report the `XTMODKEYS` state, in which case this conflict could be avoided, but I never heard back from him again.

And if things remain as they are, I suspect this is just going to end up creating compatibility issues for app devs. I know VTE is definitely opposed to supporting the `XTQMODKEYS` query, because of the incompatibility with DEC/ANSI.

**Comment by ghgary** [comment]
The last I heard from him was December 3, when he said he would contact Thomas Dickey. His initial response was so quick that I'm surprised that it's taken so long to resolve this. On the other hand, it's Christmastime and a lot of folks are really busy.

Regards,
Gary

----------------------------------------

**Comment by mintty** [comment]
> Did you ever get a reply from Thomas about this?

Yes, let me quote some of his response below. I agree those printers are "antique" and the manual you referred to in the other issue lists only a few private SGR codes, half of which were already marked deprecated even at that time. This is indeed DEC printer stuff, not DEC terminal stuff and not ANSI stuff either as I see it. So I decided compatibility with current xterm features is certainly more worth than those exotic sequences.

This is some of what Thomas wrote me:

> I'm not really interested in DEC printers (aside from having used the character-set information to help fill in details of the NRCS stuff).
> 
> Printers using escape sequences have been very rare over the past 25-30 years.
> 
> Technically ncurses supports printcap, and "could" maintain a database of that,
> but in fact the existing Unix printer stuff in the terminal database dates back to the late 1980s.
> 
> ...
> 
> So... when I went to determine what code was available, I checked the DEC terminal manuals, found nothing.  What I came up with seemed to fit.
> 
> ...
> 
> I added the two query-features to help Bram Moolenaar, who had thought that the XTGETXRES stuff would tell him the state of XTMODKEYS.
> 
> It doesn't do that - so I added the two new features to work with the cases where xterm's using state that is set via resources, but thereafter couldn't be queried.
> 
> Bram may find some scenario where he wants some changes, but for now I don't see a need to change it.  (I suspect he's not concerned with antique printers either).

**Comment by j4james** [comment]
> This is indeed DEC printer stuff, not DEC terminal stuff

The problem with making that assumption is that one of the main goals of the ANSI standard was to achieve interoperability between a diverse set of applications, including word processors, printers, and terminals. The idea being that you could markup a document with ANSI sequences, and render that straight to a terminal or printer, and expect a reasonable level of compatibility between the two. This is why you have things like _Printer Controller Mode_.

So in the case of `DECSGR`, it's not unreasonable to suppose there are legacy document management systems in use somewhere that have superscript and subscript marked up with `DECSGR` sequences, and the expectation would be that you could view them directly on a DEC-compatible terminal or printer. It's not a big deal if the terminal just sees something like H2O rather than H₂O, but it certainly wouldn't be expected to trigger a query response.

> not ANSI stuff either as I see it

Quoting the ANSI standard from section 3.5(3): "F is the function defining character. It is used either as itself or with the I characters(s) to establish what function is encoded". In the case of `CSI ? 4 m`, the F character is `m`, and there are no I characters, so that establishes it as an `SGR` function.

Then from section 3.5.6: "If P11 is 3/12 to 3/15, inclusive, the entire parameter string is subject to private or experimental interpretation." So the `? 4` part is considered a _private parameter string_ on the `SGR` function.

So if you wanted to use `SGR ? 4` for some other form of rendition, like say wavy underlines, that would seem perfectly reasonable. But to use `SGR ? 4` as a query sequence for a keyboard protocol is ridiculous - that's clearly not what the standard intended. If you wanted to define a completely different control function there's a protocol for that.

Anyway, if you want to remain compatible with XTerm, I suppose you don't have any choice, but I think XTerm's behavior here is very wrong. Not just in terms of the standards, but in thinking he can overwrite sequences that other terminals were already using and everyone else just has to give in. And as I mentioned above, I don't see VTE giving in, so one way or the other we're likely to end up with conflicts here.

But thank you for letting me know Thomas' response. At least I know now that he's definitely not going to back down.

**Comment by mintty** [comment]
> Quoting the ANSI standard from section 3.5(3): "F is the function defining character. It is used either as itself or with the I characters(s) to establish what function is encoded". In the case of CSI ? 4 m, the F character is m, and there are no I characters, so that establishes it as an SGR function. ...

Well, yes. But this is the wrong place for the argument, as you say yourself. As xterm is the archetype of terminal behaviour for mintty, you'd need to convince Thomas Dickey and Bram Moolenar to change the sequence.

**Comment by j4james** [comment]
@mintty FYI, the latest version of XTerm (patch 389) now has support for querying the state of `XTMODKEYS` with a standard `DECRQSS` sequence.

**Comment by mintty** [comment]
Released 3.7.1.
