### ISSUE TITLE
CMake build support?

### ISSUE THREAD

**Issue by ewancg** [mintty/mintty#1222]
Makefiles generally leave a lot to be desired nowadays. I haven't looked too deep into it but it seems that what's happening in the mintty makefiles can be easily reproduced in CMake using established idioms (CMakeLists.txt for each subdir, different build targets, etc). I think it would work quite well and make development setup a bit easier for folks not used to working with makefiles or those who want to integrate into their IDE. Thoughts?

**Comment by mintty** [comment]
Never change a running system. I see no benefits but lots of effort.

**Comment by BrianInglis** [comment]
As `mintty` has been under almost continuous improvement for 15 years since it was forked from `putty`, with other contributions and lots of suggestions, by mainly two volunteers, with a unique mix of *Windows* screen and *Cygwin* `pty` terminal I/O, built using *Cygwin* cross-/tools to work as the default native *Windows* terminal interface, not requiring *X*, for *Cygwin* shells, `screen`, `tmux`, *Git-for-Windows*, and other *Windows* console interfaces: it would be perverse to require non-core build tools. 

Anyone and everyone is encouraged to provide any contributions they would like to add, under the *Cygwin* and `mintty` licence terms, so you and they are all invited to understand the current build configuration, tools, process, and configuration options, files, and docs, and port *everything* to some alternative build process, document that, and add the files to the package, running the standard *Cygwin* package build process, which already understands and supports all common alternative build tools, producing an identically linked and functioning *Windows* screen terminal app that handles *Cygwin* `pty` I/O, other *Windows* and *Cygwin* interfaces and features, `xterm` terminal emulation escape sequences and features including *Tektronix* vector graphics storage scope emulation, *VT...* character sets and *ReGIS* graphics, plus *WSL* and other console interfaces.

**Comment by ewancg** [comment]
>Never change a running system. I see no benefits but lots of effort.

I was thinking that if implemented, the CMake build files would go alongside the makefiles. You're right, there is no point in disturbing something that works as-is. This does not mean, however, that there is *no* benefit to using CMake as well, even if there's no benefit to it in *your* workflow; most IDEs supporting C and C++ provide CMake integration, so if mintty supported CMake it would significantly simplify the process of editing the project for those who use these IDEs (the alternative obviously being the text editor + terminal combo, which is great, but not for everyone).

I think most people would rather not set up project-specific build files or use their IDE as just a text editor. Many IDEs also provide context-specific features, such as:
- code analysis, which can break if not set up to reflect the project's constraints like defines, includes/include order, language spec, etc.
- auto build/run, which doesn't work outright if not attached to a build system & the absence of it often requires tabbing out to another window (or some other, equally irritating action).

CMake leaves little to no gray area in this regard, because you can specify everything I just listed. I think that's a reason that integration both in code and in code editors is so increasingly common.

@BrianInglis, I appreciate your feedback, but I'm not sure if I'm intended to take it as an invitation to implement it, or as a message to not interrupt the current flow of things. You say this:
> Anyone and everyone is encouraged to provide any contributions they would like to add...

but you also say this.
> ...so you and they are all invited to understand the current build configuration...

I may also be seriously misunderstanding the scope of this build system. I didn't consider that the effects of its changes could extend past just mintty. Please let me know what you mean.
