### ISSUE TITLE
Transparency is lost when resizing snapped window.

### ISSUE THREAD

**Issue by CoeJoder** [mintty/mintty#1256]
When the wsltty window is snapped to the side of the screen and resized, transparency is lost and must be reset in the options.  See video clip.  I only noticed it after the most recent Windows 11 update.

O/S: Windows 11 Pro, version 22H2
wsltty 3.7.0.2 (64-bit)

https://github.com/mintty/wsltty/assets/3125461/f8c4a9f4-79d4-40c2-987b-5e3a94846556

**Comment by mintty** [comment]
Transferred this issue to mintty as it is not wsltty-specific.
In the described situation, a mintty window that does not have the focus is being resized by means of snap/grid adjustment using a Windows 11 feature. (Possibly reproducible in Windows 10 with some window manipulation software, don't know.)

In this scenario, apparently the mintty window is forced into opaque (non-transparent) mode by Windows without changing its related parameters (GWL_EXSTYLE and the GetLayeredWindowAttributes alpha value are not affected).
During this resize, a much smaller sequence of messages are sent to the window than otherwise when resizing:
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
WM_SIZE
WM_WINDOWPOSCHANGING
WM_PAINT
WM_ERASEBKGND

Furthermore, calling win_update_transparency later does not recover transparency as long as the alpha value is not changed.
Therefore the current patch adds a flip to opaque and back to alpha call to that function.
Trying to add an invocation of win_update_transparency to any of the above messages did not solve the issue however. Therefore, I'm setting the "Help wanted" flag on the issue.
At least this change will recover transparency as soon as the window is activated again, so it's an improvement.

**Comment by mintty** [comment]
Released 3.7.1.
