### ISSUE TITLE
`GetSystemTimePreciseAsFileTime` not found in dll `kernel32.dll`

### ISSUE THREAD

**Issue by kralo** [mintty/mintty#1298]
cannot start mintty on windows 7.
part of git / msys2

mintty version 3.7.6.0

could there be a workaround made "if OS>WIN7 use preciseFileTime else not..."

![grafik](https://github.com/user-attachments/assets/0fd58fd8-6acb-43e5-b1d6-16aaac04899f)

**Comment by avih** [comment]
FWIW, I recently handled this in another context, like so:

```c
#define procaddr(x,y) (void(*)(void))GetProcAddress(x,y)  /* else gcc warns */
typedef void (WINAPI *t_gst)(FILETIME*);  // GetSystemTime[Precise]AsFileTime
static t_gst getSysTimeFT_ = 0;

static void time_init(void)
{
    // non-percise is limited by timeBeginPeriod, precise only in newer windows
    HANDLE h = LoadLibrary("kernel32");  // already loaded, procaddr verifies
    if (!(getSysTimeFT_ = (t_gst)procaddr(h, "GetSystemTimePreciseAsFileTime")))
        getSysTimeFT_ = GetSystemTimeAsFileTime;
}
```

**Comment by mintty** [comment]
Mintty was tested on Windows 7 as documented on http://mintty.github.io/ and it does not call that function directly.
So maybe it's something particular to MSYS2. It will need some investigation to find the root cause and the workaround above will not help in this case. What's the version of Windows 7 and of Git for Windows/MSYS?

**Comment by BrianInglis** [comment]
> Mintty was tested on Windows 7 as documented on http://mintty.github.io/ and it does not call that function directly.

In fact `mintty` seems to call `gettimeofday`(3p) giving `s + us` since Unix Epoch, and `clock_gettime`(3p), mainly with `CLOCK_MONOTONIC` `s + ns` since boot, but also `CLOCK_REALTIME` `s + ns` since Unix Epoch, resolution *MS Windows* 0.1us/100ns units, under *Cygwin*. 

There also appears to be some use of *MS Windows* timer APIs? 

Perhaps *Msys2* provides different/non-*POSIX*? implementations of `gettimeofday` and `clock_gettime`? 

In [measuring elapsed time on mingw](https://lists.gnu.org/archive/html/bug-gnulib/2010-04/msg00077.html) Eric Blake notes that the usual *MS Windows* timing functions can have resolutions from 1/64s 15.625ms to 1ms, depending on other processes on the system.

**Comment by avih** [comment]
> Eric Blake notes that the usual _MS Windows_ timing functions can have resolutions from 1/64s 15.625ms to 1ms, depending on other processes on the system.

It depends on whoever set `timeBeginPeriod`, if at all.

By default it's indeed 1/64s, but many apps increase it to 1ms resolutions (sometimes permanently until they exit, like Skype), and it's a global thing, so all other apps see the highest resolution which any app set at any given time.

I'm guessing there's no issue with CLOCK_MONOTONIC because that's likely implemented using QueryPerformanceCounter which doesn't depend on timeBeginPeriod, but for CLOCK_REALTIME the underlaying cygwin/msys2 implementation is likely using GetSystemTime[Percise]AsFileTime, where both return the value in the same units (100 ns intervals since 1601-01-01 00:00), but the non-percise function "updates" at best every 1ms, and by default ~15.6 ms (depending on timeBeginPeriod), and the Percise variant has real 100 ns resolution regardless of timeBeginPeriod.

So I think it's possible that msys2/cygwin switched to the percise variant once windows 7 support got dropped (I believe the percise variant is supported on win8 and later), and therefore if mintty uses `clock_gettime(CLOCK_REALTIME, &c)` then the underlaying implementation might be trying to use the percise variant, but failing to find it on win7.

**Comment by BrianInglis** [comment]
The [Compatibility](https://mintty.github.io/#compatibility) test matrix shows successful `mintty` testing under *MS Windows* 7 and earlier releases, running under the appropriate *Cygwin* release to support the legacy release and bitness (and *Msys* for *W2K*!) 
Please see the instructions for the [Cygwin Time Machine](http://www.crouchingtigerhiddenfruitbat.org/Cygwin/timemachine.html) setup program releases, setup.ini files, and options and arguments required for each legacy release.

**Comment by avih** [comment]
Git-for-Windows just updated their website that the last supported version for windows 7 is 2.46.2 - https://github.com/git-for-windows/git/issues/5280

I'm guessing exactly because they switched to msys2/cygwin runtime which dropped support for win7, and technically possibly due to unconditional use of GetSystemTimePerciseAsFileTime, among others.

So IMO this issue can be closed, as GFW 2.47.x is not supported on win7.

**Comment by avih** [comment]
> ... but for CLOCK_REALTIME the underlaying cygwin/msys2 implementation is likely using GetSystemTime[Percise]AsFileTime, where both return the value in the same units (100 ns intervals since 1601-01-01 00:00), but the non-percise function "updates" at best every 1ms, and by default ~15.6 ms (depending on timeBeginPeriod), and the Percise variant has real 100 ns resolution regardless of timeBeginPeriod.
> 
> So I think it's possible that msys2/cygwin switched to the percise variant once windows 7 support got dropped

For future reference, this is exactly what happened with CLOCK_REALTIME when they dropped win7 support, at `clk_realtime_t::now` - https://github.com/cygwin/cygwin/commit/70d77662f5742718eb37dbd9e373fe7ab12b8c36#diff-49b7568b57a221d6d886e527b37d37d98a8818fa146078cc68ca1b6cd5f2c9adL77

**Comment by kralo** [comment]
ok, thanks for all the info
