### ISSUE TITLE
Underscore as font style and color

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#249]
```
Would it be possible to enhance mintty so that in man pages the underscored 
text would show up as blue, like what is shown when using Cygwin to view man 
pages? (I'm using mintty 0.9.5)  I really like mintty, but miss the improved 
man page readability I got with Cygwin.

Attached are screenshots of the mintty man page viewed in both Cygwin and in 
mintty.
```

Original issue reported on code.google.com by `ambl...@gmail.com` on 10 Feb 2011 at 10:44

Attachments:
- [cygwin.jpg](https://storage.googleapis.com/google-code-attachments/mintty/issue-249/comment-0/cygwin.jpg)
- [mintty.jpg](https://storage.googleapis.com/google-code-attachments/mintty/issue-249/comment-0/mintty.jpg)

**Comment by mintty** [comment]
For the records:
man pages typically use the *italic* attribute, not underline, for some highlighting;
this is by default remapped to underline by the tool `grotty` which is part of the `man` invocation workflow.

Mintty supports actual *italic* since release 2.0.1.
My package `man-italic` (proposed for cygwin) patches the `man` workflow to actually use *italic*.
