### ISSUE TITLE
mintty occasionally loses the last output of the program

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#402]
```
screencast attached

windows xp
MSYS 1.0.18(0.48/3/2) 2012-11-21 22:34 i686 unknown; targ=MINGW32
mintty 1.0.3


```

Original issue reported on code.google.com by `bdim...@gmail.com` on 21 Aug 2013 at 10:53

Attachments:
* [mintty-loses-last-output-of-the-program.7z](https://storage.googleapis.com/google-code-attachments/mintty/issue-402/comment-0/mintty-loses-last-output-of-the-program.7z)

**Comment by mintty** [comment]
This sounds to be most likely a MinGW issue rather than a mintty issue.
I vaguely remember that similar problems have been discussed on the cygwin mailing list and fixed since. As MinGW is an old fork from cygwin, there isn't much to be done, unless you would dig out the cygwin fixes and back-port them to MinGW.
