### ISSUE TITLE
Incorrect displaying of pasting from the clipboard when the text contains cyrilic chars

### ISSUE THREAD

**Issue by Andrey-Bushman** [mintty/mintty#461]
I want to write some settings into common config file of Git for Windows (Git Bash). Command is long. I try to past this command from clipboard. It has cyrilic chars (Отдел) also:

`git config -f "\\\\hyprostr\\dfs\\groups\\Отдел IT\\@Bush\\dev\\settings\\gitconfig.txt" http.proxy http://@proxy2:8080`

but I see incorrect displaying of pasting result in Git Bash. Look an attached screen. Can I fix it?

![_0](https://cloud.githubusercontent.com/assets/10530134/8671059/a66c7cda-2a2a-11e5-8d77-732f934615dd.png)

**Comment by mintty** [comment]
I can reproduce the issue with MINGW mintty and MINGW bash. Not related to git. Likely not related to mintty either: Run cat, then paste the line and get it echoed. Both lines (input and output of cat) display fine.
So I guess it's a problem with bash which is probably not sufficiently (or at all?) locale-aware on MINGW.
I does not account for the proper width of UTF-8 characters and gets confused with line wrap-around.
Test case:
Resize the terminal window so that the full paste text fits on one line - surprise: the text pastes fine!

**Comment by Andrey-Bushman** [comment]
But what if I am not a happy owner of the monitor 4 meters wide?

**Comment by mintty** [comment]
Just a joke? Half a meter is fine for the line you quoted...

**Comment by Andrey-Bushman** [comment]
What about without joking?

**Comment by kostix** [comment]
Well, Andrey, not being a native speaker, you have probably took offence while there wasn't any, so please calm down. ;-)

Johanness, when closing your original bug report, merely suggested this bug *might* be in `mintty`, and hence it perfectly may be located somewhere else.

The `mintty` maintainer presented you with a test case which demonstrates that the likely problem is in `bash` because pasting into `cat` running in that same `mintty` works.

So I'm afraid the next destination on your trip is [the MinGW bug tracker](http://sourceforge.net/p/mingw/bugs/) or [their mailing lists](http://mingw.org/mailing_lists) -- all these resources are described [here](http://mingw.org/Reporting_Bugs).

I do think I can understand your pain but that's how volunteer-supported projects work: if the think breaks you have to hold both pieces yourself. ;-)

**Comment by Andrey-Bushman** [comment]
Ok, I posted it here: https://sourceforge.net/p/mingw/bugs/2265/
I hope it is correct location of my issue.
