### ISSUE TITLE
charset GBK

### ISSUE THREAD

**Issue by zeroleo12345** [mintty/mintty#463]
when i run command as below, it occur error：  bash: cd: E:\妗岄潰: No such file or directory
mintty.exe -e /bin/bash --login -i -c "cd 'E:\桌面';exec bash"

.minttyrc is set as below:
……
Locale=C
Charset=GBK
Term=xterm
……

when i set Charset=UTF-8, it works for cd.but can't handle chinese well.
after i update cygwin64, this error occur.Just happend in my environment ?

**Comment by mintty** [comment]
The reason is character encoding inconsistency between the invoking environment and the invoked terminal:
In the invoking shell, the locale has a UTF-8 encoding. Thus the command you enter and pass to mintty is UTF-8 encoded. The according byte sequence is then passed to the shell within the mintty but now it's being interpreted as GBK, with a different meaning.
This is a genuine problem of switching character encoding and not related to mintty, thus I will close the issue soon.
Workaround:
1. Run the surrounding command environment in GBK too (if it's a cygwin console, though, you will not have font support for CJK).
2. Embed the command line in a shell script and make sure it is GBK-encoded.

**Comment by mintty** [comment]
You can actually verify that this is a generic problem by substituting mintty with urxvt, or simply with a shell:
LC_ALL=C.GBK /bin/bash --login -i -c "cd 'D:\桌面'; exec bash""
bash: cd: D:\桌面: No such file or directory

In this case, although what happens is quite clear for the insider, the test case is confusing as it actually looks as if the proper directory would not have been found.
The reason is, as explained before, that the shell, running in GBK encoding, does not use the correct directory path; but the error is reported back into the invoking UTF-8 environment where it looks proper again...

**Comment by zeroleo12345** [comment]
i use it to open the mintty on the right mouse menu in win7, so now i only run the command in new bat with translating the char to gbk first?

**Comment by mintty** [comment]
yes, or you could edit the menu entry, entering the name there using GBK; then it would work but appear wrong on the menu :/

**Comment by mintty** [comment]
Another option would be to include a conversion in the command line:
... bash -c 'cd `echo D:\桌面 | iconv -f UTF-8`; exec bash'

**Comment by zeroleo12345** [comment]
"F:\Program Files\cygwin64\bin\mintty.exe" -i /Cygwin-Terminal.ico -e /bin/bash --login -i -c "cd `echo '%V' | iconv -f UTF-8` ;exec bash"

it work fine.THX

**Comment by mintty** [comment]
Adding the issue to the wiki Tips section.
