### ISSUE TITLE
2.1.3 breakes conemu

### ISSUE THREAD

**Issue by fhoshino** [mintty/mintty#466]
Mintty updated to 2.1.3, conemu will fail to capture the window due to spawning of process.
2.1.2 works fine with conemu.

https://github.com/Maximus5/ConEmu/issues/239

**Comment by Maximus5** [comment]
The problem was with daemonizing. Well, adding `-d` switch will solve the problem, but...

1. This switch leads to an error if is used with previous mintty builds.
2. It's wrong, I believe, to let users to add `-d` switch manually. Damn, nobody reads docs.
3. I can't add the switch automatically because of (1).

So, may be you will not do forking/daemonizing if your app was started from ConEmu? Easiest way to check this - environment variable: http://conemu.github.io/en/ConEmuEnvironment.html#List_of_environment_variables_set_by_ConEmu for example ConEmuPID.

**Comment by mintty** [comment]
Disable the process-spawning with command line option -d.
The spawning was introduced to ensure signals are being delivered within mintty, which would otherwise not happen if started from a console window. I have no idea whether being invoked from ConEmu could be detected automatically, thus the option will likely be needed in future.
Also, please tell me whether in mintty -d, or older mintty, signals work (e.g. Control-C interrupts).

**Comment by Maximus5** [comment]
Ctrl-C interrupts "ls -R" properly at least when mintty is running in ConEmu tab. Either old mintty build, or new one with `-d` switch doesn't matter, all work.

Checking environment variable, as I've said, is the simplest way.

If you need test, you may download ConEmu, unpack it and run `ConEmu.exe -basic -cmd c:\cygwin\bin\mintty.exe -`

**Comment by mintty** [comment]
Cannot test right now because it tells me:
---------------------------
ConEmu 150728 [32]
---------------------------
Can't create new console, check your antivirus (code 5)!
Access is denied.
...
(will test on a different machine)

**Comment by Maximus5** [comment]
This weirdness is unexpected of course... Can you please send me log files?
http://conemu.github.io/en/LogFiles.html

    ConEmu -basic -log -cmd path-to-mintty

Do you have some antivirus software installed?

**Comment by mintty** [comment]
There are no log files anywhere, and yes there's a strong antivirus policy on this machine, that's why I need to test elsewhere. (It's Trend Micro Office Scan, maybe you'd like to report them a false positive for ConEmu.)

**Comment by fhoshino** [comment]
@mintty http://conemu.github.io/en/LogFiles.html

**Comment by Maximus5** [comment]
Antiviral software producers doesn't accept reports from non-clients in general.
Where have you looked up for logs?

**Comment by mintty** [comment]
While this isn't really about mintty... I downloaded the portable version, started from unpacked folder, no log file in there or on the desktop, or in C:...program files...

**Comment by fhoshino** [comment]
@mintty If you are using the portable version, the log files should be generated in the same folder in the portable executables.

**Comment by Maximus5** [comment]
Have you started it with -log switch?

**Comment by mintty** [comment]
OK, the log file does not contain anything related to terminate, access denied and such.
(And I'll not post it here.)
Don't mind if I'll later remove all log-file related comments here.

**Comment by Maximus5** [comment]
Link to cygwin topic: http://comments.gmane.org/gmane.os.cygwin/154167

**Comment by mintty** [comment]
The strange virus message occurred on my other machine as well (this one running aVast).
Anyone, I could try in a VM running Windows XP.
(Deleting this comment along with ConEmu-related ones.)

**Comment by mintty** [comment]
As suggested, the workaround checks for $ConEmuPID although that's not strictly a safe indication; but starting an "outside" mintty from there works as well, so that should be fine.
