### ISSUE TITLE
Text change size (becomes tiny) when window changes screen

### ISSUE THREAD

**Issue by mestreniko** [mintty/mintty#487]
When a window is maximized in one screen, if it's dragged and dropped in another screen the text size changes (becomes tiny) and I need to do ctrl+0 to restore text to the normal size.
It doesn't happen if the window is first restored.

**Comment by mintty** [comment]
Can we remove the references to 486 please as that is completely unrelated?

**Comment by mestreniko** [comment]
I removed the references.

**Comment by mintty** [comment]
This happens since mintty 2.1.1 due to the new feature Shift-coupled font-with-window zooming (#204).
It should only occur if you hold Shift while dragging the window. The purpose of that feature is to zoom the font so that the terminal size stays the same.

In this issue, the zoom feature apparently interferes with the fact that full-screen mode is reverted if the window is dragged to another screen (which has always been the case and is probably some Windows feature) and this is not considered with the new feature (yet).

**Comment by dcbrwn** [comment]
+1 and I'm dragging mintty window without holding shift key. DPI on both monitors are the same. Actually both monitors are same, resolution and so on.

**Comment by mintty** [comment]
What if you move with the Windows hotkeys, Win+Shift+cursor-left/right, as a workaround?

**Comment by dcbrwn** [comment]
@mintty, yep. it works this way. thanks!

**Comment by rupor-github** [comment]
Would like to propose fix for this one and #492 - it is a bit simpler than Takashi Kawasaki's change (espresso3389). I tested it with WIndows shortcats and also by moving mintty window between screens with very different DPIs (96 & 192, 96 &144 - with and withou DPI scaling enabled). Should I open pull request - https://github.com/rupor-github/mintty?

**Comment by mintty** [comment]
Great, thanks! I'll check that next week.
If you'd like a pull merged, may I ask for uniform formatting please: 2 spaces indentation, no TABs.

**Comment by rupor-github** [comment]
Thank you, I fixed code formatting and opened pull request.

**Comment by mintty** [comment]
Hmm. I see no different behaviour on Windows 7. If I maximise, then drag to another screen, the window is restored (not maximised) but the font size remains. Only if dragged with Shift, the font size becomes tiny. Same with your patch.
Maybe it's only helpful on Windows 8?
Also, we should make sure that issue #470 isn't broken by the [patch](https://github.com/mintty/mintty/pull/505.patch); @espresso3389, do you have time to test that?

**Comment by rupor-github** [comment]
I do not really know - do not have Windows 7 any more. Tested under Windows 10 - and I did not realize that I have to maximize window :) Will look into this some more.

**Comment by rupor-github** [comment]
I think real reason for this problem is the fact that during WM_EXITSIZEMOVE message processing call to win_adapt_term_size(shift, false) is wrong. It should be something like win_adapt_term_size(false, shift) instead.

I also think that logic related to font scaling is a bit over-complicated in general, particularly with zoom_token. So I tried to correct this - it seems to solve other scaling issues too. 

Please, take a look at https://github.com/rupor-github/mintty - as I may not be aware of all the details it is quite possible that I am missing something here.

**Comment by ElvenSpellmaker** [comment]
I'm not sure if this is a separate issue, but it seems related to this issue and so I'll comment on it here.

If you use the shortcut for fullscreen (`Alt+Enter`) with the shift key held down (`Shift+Alt+Enter`) then the font size first gets larger (5 times above 100%, like pressing `^+` 5 times), and gradually gets smaller and smaller on each successive press of the combination until the zoom 
factor gets to the lowest possible and then it reverts back to 100% again and continues the cycle of, once large and then gradually zooming out.

Weirdly this doesn't happen if the zoom factor is over a certain amount beyond 100%, which for me seems to be _4_ `^+` keyboard commands (zooming in 4 times over 100%)

**Comment by mintty** [comment]
Alt+Enter toggles full-screen, so the second pressing should restore the window to normal size.
If you mean the third (5th, etc) Shift+Alt+Enter to change the zoom factor, I don't see it here right now, but it may happen; quoting from the manual page: `(Note that due to the different height/width factors, this is not a precise operation)`

**Comment by digulla** [comment]
I updated to the latest cygwin 2.5.2 today. mintty --version says "2.4.0" I'm on Windows 8.1 Professional.

I have two identical monitors with the same DPI settings. Whenever I move a mintty window from one screen to another using the mouse, the font and the window gets bigger.

I'm not pressing Shift while moving windows. Using Win+CursorKey doesn't show this effect.

**Comment by mintty** [comment]
That's not the issue being discussed here. It's actually #566 and was fixed in 2.4.1.

**Comment by mintty** [comment]
I've tentatively revised DPI change handling to hook into WM_WINDOWPOSCHANGED rather than WM_DPICHANGED.
Please test the repository version (not making a release now before 3-week travelling).

**Comment by mintty** [comment]
Revised DPI handling as described in https://github.com/mintty/mintty/pull/470#issuecomment-241581145; release in 2.5.0 (cygwin test version).
Please check whether that fixes this issue.

**Comment by dcbrwn** [comment]
Checked v2.5.0. Works as expected.

Good job!

**Comment by mintty** [comment]
I have seen similar behaviour as a consequence of interference with Aero-Snap. Switching off Aero-Snap fixed this for me.

**Comment by mintty** [comment]
Released revised DPI handling in 2.5.1; assuming this issue is resolved, too, unless Aero-Snap interferes.

**Comment by apeteri** [comment]
Just a heads-up, the FancyZones feature of Windows 10 PowerToys also uses Shift to show snap regions (when the corresponding "Enable zones while dragging with the shift key" setting is enabled): https://github.com/microsoft/PowerToys/wiki/FancyZones-Overview#settings

**Comment by jpweytjens** [comment]
> 
> 
> Just a heads-up, the FancyZones feature of Windows 10 PowerToys also uses Shift to show snap regions (when the corresponding "Enable zones while dragging with the shift key" setting is enabled): https://github.com/microsoft/PowerToys/wiki/FancyZones-Overview#settings

A workaround with `.minttyrc` can be found [here](https://github.com/microsoft/PowerToys/issues/3196#issuecomment-682351624).

**Comment by apeteri** [comment]
It did work, thanks for the link!

**Comment by mintty** [comment]
mintty 3.4.1 will also override font zooming behaviour when Ctrl is pressed, too. So with Shift+Ctrl+movement you'd snap to a fancy zone without font zooming

**Comment by mintty** [comment]
Released 3.4.1.
