### ISSUE TITLE
Scrollback Search activates Transparency on Lost Focus

### ISSUE THREAD

**Issue by ElvenSpellmaker** [mintty/mintty#497]
The `Alt+F3` scrollback search activates the transparency as if the window has become unfocussed. This makes it hard to look at the content while searching.

Pretty sure the window should count as focussed still.

**Comment by mintty** [comment]
@kiwiz: Might you have any idea?

**Comment by kiwiz** [comment]
Since we have two windows now, we can't listen for the `WM_SETFOCUS` event. This gets fired whenever the main console pane loses focus to the search bar. 

Instead, we can watch for the `WM_ACTIVATE` message to determine whether the window is active. I've made the necessary changes in the diff below. However, the caret will act oddly if you have your cursor set to blinking. This is probably because the screen is getting redrawn on every cursor blink, causing the search caret to disappear.

To resolve this, I think some refactoring of the code to not use `has_focus` will be necessary. However, before I attempt that, I want to see if anyone has a better idea.

[tmp.txt](https://github.com/mintty/mintty/files/44568/tmp.txt)

**Comment by mintty** [comment]
Thanks a lot for the quick semi-fix. I have no cursor in the search bar, though, regardless of blinking.

**Comment by mintty** [comment]
After some tweaking of focus handling, uploaded fix. Please check.

**Comment by kiwiz** [comment]
Looks good to me! I was afraid this would require a lot more refactoring, but this works just fine. :+1:

**Comment by mintty** [comment]
Released in 2.2.3.
