### ISSUE TITLE
Pasting junk

### ISSUE THREAD

**Issue by txdv** [mintty/mintty#620]
Hey guys,

I'm trying to paste stuff into my mintty and it adds 0~ at the front of my paste and 1~ at the end.

I noticed that this happens every time I lock my screen, go to home and next morning when I login again every terminal still open has the same issue (I need to close them and open a new one to circumvent this issue).

I'm using the mintty provided with msys2

Is anyone else experiencing a similar issue?

**Comment by mintty** [comment]
These are the visible remains of the brackets embedding the pasted text in bracketed paste mode.
Bracketed paste mode is switched by escape sequence ESC[?2004h (on) ...l (off).
Somehow this sequence must be sent to your terminal before the effect arises, please check.
Instead of restarting the terminal, you can send it the "off" sequence, or run the `reset` command.

**Comment by mintty** [comment]
... or use "Reset" from the context menu, actually, or its shortcut Alt+F8.

**Comment by txdv** [comment]
The command line is talking to me ... thanks for the advice, I will try it out!

**Comment by txdv** [comment]
Now I just got a ~ prefix and suffix, but the reset helped, thanks.

**Comment by mintty** [comment]
It would still be interesting to find out how the enabling sequence is getting sent to your terminals.
