### ISSUE TITLE
interrupting windows-native program makes mintty stall

### ISSUE THREAD

**Issue by chaosreload** [mintty/mintty#688]
I found that when I try to use windows-native redis-cli in mintty, it hangs and mintty crash, I even can not use 'Ctrl + C' to stop it. 
Other interactive programs just hang in console and you can use 'Ctrl + C' to stop, like [the issus #56 ](https://github.com/mintty/mintty/issues/56).
Seems the windows-native redis-cli more harmful to mintty.

**Comment by mintty** [comment]
It would be helpful to provide a reproducible test case; where do I get that program or how can I build it?
Alternatively, or additionally, please make a log: start `mintty -l .logfile` and upload the .logfile here.

**Comment by mintty** [comment]
Please describe the symptom precisely; I assume you mean "stall" rather than "crash" (i.e. the window does not respond anymore and is greyed by Windows). That actually happens occasionally after Windows programs are interrupted. It's related to pty and signal handling incompatibilites; the actual stall arises in a `write` call. Maybe it's possible to make mintty handle this more gracefully, like xterm.
Assuming this is the incident you refer to, I'll change the title.

**Comment by mintty** [comment]
Actually, xterm does not necessarily handle this issue more gracefully; I've reproduced a complete stall in xterm in the same situation. This confirms it's not a mintty issue. Closing.

**Comment by chaosreload** [comment]
sorry for late reply @mintty , I tried it in cygwin with mintty actually. 
I found that when I use cygwin with cmd console, redis-cli does not stall, while in mintty it does, so I surmised that it's mintty's issue. 

I will check out the log with `mintty -l .logfile`, thanks!

**Comment by mintty** [comment]
Cygwin 3.1.0 has been released with ConPTY support. Please recheck.
