### ISSUE TITLE
Italic (slanted) text is gibberish after some time running

### ISSUE THREAD

**Issue by avih** [mintty/mintty#725]
Using mintty 2.8.2

When running `printf "\033[3mxxx\033[m"` right after starting mintty, then it indeed prints `xxx` in italics:
![italic-good](https://user-images.githubusercontent.com/2164962/34319074-9f3796d6-e7e0-11e7-8f15-14d6449c4739.png)

But after some time, running the same command prints gibberish:
![italic-bad](https://user-images.githubusercontent.com/2164962/34319075-a5a0ff44-e7e0-11e7-8994-d36a3b5fa4c8.png)

I don't know what triggers it and I don't recall exactly for how long mintty has been running, but it's been few days.

I don't have exact steps to reproduce.

Edit: on closer inspection, it seems to correctly print the chars in italics , but on top of question-mark-in-a-box chars.

Using Consolas font, without any specifically set locale (this system runs in en-US).

**Comment by mintty** [comment]
Hmm. I can quickly reproduce similar (same?) overwriting effects with an endless loop writing short/long italic strings.
This is broken since 2.7.6 and I have the uncomfortable suspicion something is wrong with the italic chunk stack (term.c).

**Comment by mintty** [comment]
Actually, for me the bug seems to have disappeared with 2.8.2, presumably a side effect of:
  * Fixed non-BMP italic display.

Are you sure about the version?

**Comment by avih** [comment]
> Are you sure about the version?

Pretty much. The executable is from Dec-16 and options->about says 2.8.2 . It does have 2 minor msys2 patches on top, but they never get close to rendering (just add an icon and a startup dialog to choose msys2/mingw32/mingw64 shell).

Can you share the program or script you used to reproduce it? I'll try it too.

**Comment by mintty** [comment]
```
while true
do
        printf "\033[3mxxx\033[m"
done
```

**Comment by avih** [comment]
Huh.. well.. I tried this loop, and others, but I can't reproduce it.

Do you think it could be related to the duration mintty has been running? or more likely a specific trigger which started it? (and from then it kept having broken italics until I closed the mintty window and opened a new one).

**Comment by mintty** [comment]
This will need some dedicated tracing and analysis. Probably not this year.

**Comment by avih** [comment]
FWIW, it hasn't happened since, and I still use the same mintty version. I'll post here if it happens again, and will try to keep the window open for further diagnostics. But for now, all good. I guess it needs some rare condition to trigger it...

**Comment by mintty** [comment]
Analyzed this embarrassing bug:
In term.c, for each chunk of consecutive output (within a line), there is a distinction:
          if (attr.attr & (ATTR_ITALIC | TATTR_COMBDOUBL))
            push_text(...);
          else
            win_text(...);
Well, not quite for each chunk; I forgot to make the same distinction for the final chunk, after the loop, around line 1580.
(This does not explain why the bug seems to have disappeared with 2.8.2 for me, but maybe that's just a random observation.)

So this would be a quick fix. However, I'm considering to drop the right-to-left display for italic chunks (and thus the italic chunk stack) altogether, and use a two-pass approach instead. The revision could also encompass support for other, non-italic, overhang cases, like ambiguous-width graphics (#615), Indic characters (#553), Emojis (#671) or private range glyphs (#680).

**Comment by avih** [comment]
I'm not familiar enough with this code to follow your analysis, and it's a bit complex to begin with (nudge nudge ;) ).

Do you have a way to trigger it though? If yes, I'll try to test if my build is affected the same way as you expect, and then retry after the fix with the same trigger case.

**Comment by mintty** [comment]
You could revert to 2.8.1. More precisely, the effect seems to be hidden since https://github.com/mintty/mintty/commit/d9218754901c5d384145b1a5cc2bc66ab6603af1
"underlay manual underline below text"
(due to changed handling of the two invocations of win_text from term.c using LATTR_DISP1 and LATTR_DISP2, where the first draws the background and the second draws the italic text transparently).

**Comment by mintty** [comment]
Released 2.8.3.

**Comment by avih** [comment]
I still didn't happen again, and I moved to 2.8.3 once you released it. Hopefully that fix does fix it, but regardless, apparently it was very rare. Thanks.
