### ISSUE TITLE
Assign shortcuts

### ISSUE THREAD

**Issue by c256985** [mintty/mintty#726]
It would be useful if there was a way to assign keyboard shortcuts to specific actions. Specifically, I'd like to be able to use Ctrl+N for a new window, Ctrl+Shift+N for a new tabbed window, Ctrl+X for cut, Ctrl+C for copy, etc. Having non-standard mappings for one program just adds to the cognitive load for the program.

**Comment by mintty** [comment]
See also #705 and #645; you are asking for a more generic feature, but similar considerations apply against arbitrary redefinition of Control characters. Because mintty is a terminal, these, as being control *characters*, are supposed to be supported for input into the terminal.

Proposals of what and how to configure without losing the ability to enter control characters are welcome.

**Comment by mintty** [comment]
I intend to close this issue because it's simply too fuzzy. With the `CtrlExchangeShift` option, it's already possible to assign "New window" to Ctrl+N and "Copy" to Ctrl+C; otherwise, Ctrl+Shift+letter shortcuts are available even from the Options menu; "Cut" makes no sense in a terminal.

Shortcut-related requests with a working design proposal will be considered.

**Comment by mintty** [comment]
Released 2.9.1.
