### ISSUE TITLE
Can't set java version

### ISSUE THREAD

**Issue by pedro-pinho** [mintty/mintty#739]
I'm using mintty to execute linux commands inside widows through eclipse.

It's all fun and games until I need to use a different java version.

This project need to be on java 1.8.
I use Process Builder to open a bash window (mintty) and the commands I run need to be on java 1.6
I tried add the path to java 1.6 in classpath, in java.library.path and by hand in the command line

``JDK6="C:\Program Files (x86)\Java\jre6"
export JAVA_HOME=$JDK6
export JDK_HOME=$JAVA_HOME
echo $JAVA_HOME
echo "Calling 'java' to output the currently used java version"
java -version:"1.6" `-version``

Without any success. It shows:

`C:\Program Files (x86)\Java\jre6
Calling 'java' to output the currently used java version
Error: Unable to locate JRE meeting specification "1.6"`

I'm stuck for 3 days on this thing.
I'm assuming it's a mintty problem because if I open cmd and type 

`java -version:"1.6" -version`

it show

`java version "1.6.0_15"
Java(TM) SE Runtime Environment (build 1.6.0_15-b03)
Java HotSpot(TM) Client VM (build 14.1-b02, mixed mode, sharing)`

Weirdly enough when I type this command from a cmd that's inside the `C:\Windows\System32` folder it shows the same error. Can someone help me understand what's going on?

**Comment by mintty** [comment]
This is not in any way related to the terminal; possibly to the shell.
You do not describe all details precisely, but in a shell "C:\\..." would be a problem because \ is a shell escape character; to embed it in a Windows-style path name, single quotes would be needed 'C:\\...'.
Your command line has a single, non-matching back-quote \`, and you didn't say where you hand it to (cmd.exe, bash.exe, ...?).
