### ISSUE TITLE
Mintty stays open after ssh exits

### ISSUE THREAD

**Issue by elieux** [mintty/mintty#745]
I don't know if this is a bug, but I'd appreciate at least your expert opinion.

Steps to reproduce:
- install Cygwin x64 with OpenSSH
- run `mintty -`
- inside, run `ssh` (displays help screen)
- inside, run `exit`
- mintty stays open

Or even simpler:
- install Cygwin x64 with OpenSSH
- run `mintty /bin/ssh`
- mintty stays open

When I run `ps` from outside, it shows just one `ps` and one `mintty`.  In Process Explorer, I see a `conhost` that is spawned alongside mintty, but killing it doesn't make a difference.

Might be related to #674.

**Comment by mintty** [comment]
Does the window title begin with "[Error exit] " after `exit`?
Please try `-h never` (setting `Hold=never`).
Apparently ssh exits with exit code 255 which makes mintty stay open by default.

**Comment by elieux** [comment]
> Does the window title begin with "[Error exit] " after `exit`?

No.

> Please try `-h never` (setting `Hold=never`).

Didn't help with neither direct ssh nor with ssh through interactive bash.  No `Hold` setting in my `.minttyrc`.

**Comment by mintty** [comment]
Oh, sorry; please add this to your .minttyrc:
`ExitTitle=[Error exit]`
Does the window title now begin with "[Error exit]" after exit?
Then, since I'm not sure how to interpret your report about `Hold` and `Hold=start` is the default,
please add this to .minttyrc:
`Hold=never`
What happens now?

**Comment by elieux** [comment]
Oh, man...  I mistyped `-h never`, so that's why it didn't help.  I also didn't know that `start` was the default.  Now it all makes sense.  Thanks.

**Comment by mintty** [comment]
As exit code 255 is considered a special case, arguably mintty could add its own error message like in some other situations.
On the other hand, I think it's quite common to use 255 as a start error code, so using it as a different error code like ssh is also a bug. Please report to ssh.

**Comment by ElvenSpellmaker** [comment]
Why does mintty behave like this? Is there a logical reason to not close the window after a 255? 🤔

**Comment by mintty** [comment]
Mintty uses exit code 255 internally if it fails to start the client application.
So if your shell is corrupted, or you run `mintty -e xy` and xy does not exist, you would receive at least some feedback instead of just a blinking and closing terminal window.
I vaguely think this is common usage of exit code 255 but cannot refer to other examples right now.

**Comment by ElvenSpellmaker** [comment]
Thanks, that seems to make sense.

Isn't there a way to separate the concerns here so that a mintty error code is treated separately from a command 255?

Are there any examples of where mintty would stay open _after_ initialisation due to a 255? Perhaps it's possible to set the feature to disabled once the shell has finished initialising? (I'm just thinking aloud here.)

Or possibly mintty should display an error message in lieu of one being provided usually? Something like `'ssh' exited with code 255"`, this way users would be aware as to why their window was staying open.

I've _always_ wondered why this happens, and I had previously thought it had something to do with my other issue, but now I see it doesn't.

**Comment by mintty** [comment]
> Thanks, that seems to make sense.

Thanks, it wasn't exactly correct, however. If the child program does not exist, there will be a different message. If the client process fails on exec'ing, on the other hand, the `exec` system call returns -1, which is propagated as 255.

> Perhaps it's possible to set the feature to disabled once the shell has finished initialising?

This is not possible with the Posix process API (fork, exec, wait, ...). It would need some additional communication (message pasing, socket, maybe indirectly via the terminal...), or maybe a timer (so if the 255 exit comes after more than 1 second, it's not the exec failure).

> 'ssh' exited with code 255

I had uploaded a patch already (see above).
Another patch could simply change 255 to 1 ("EXIT_FAILURE"). Looking forward to interfering with other applications, though...

Or, thinking again, as a simple means of communication, simply send the parent process a signal before exiting with 255? I'll try that.

**Comment by mintty** [comment]
According to http://www.tldp.org/LDP/abs/html/exitcodes.html, 
126 might be a better choice to indicated `exec` failure than 255. Changing.
If there are complaints concerning other applications after the next release, I'll change it back, though.

**Comment by mintty** [comment]
Released 2.9.0.
