### ISSUE TITLE
Alignment of 「 is left instead of right

### ISSUE THREAD

**Issue by ElvenSpellmaker** [mintty/mintty#756]
In mintty the alignment of the `「` character seems to be to the very left of the cell in every font, but in other programmes this isn't the case and it's at the right of the cell:

mintty:
![image](https://user-images.githubusercontent.com/2286713/37676390-b8a794bc-2c6f-11e8-8019-948248dc55fe.png)

Word:
![image](https://user-images.githubusercontent.com/2286713/37676401-c1f64540-2c6f-11e8-9ea4-15f754dd28f6.png)

In this issue:
![image](https://user-images.githubusercontent.com/2286713/37676579-3567ea38-2c70-11e8-97ef-f46771ffef17.png)

In Powershell ISE (shows as ? boxes in normal powershell):
![image](https://user-images.githubusercontent.com/2286713/37725954-1621b1ec-2d2c-11e8-84a3-ed68f7b073f1.png)

Note: PS seems to treat it as single width, are the characters ambiguous width? Unless it's combining with the next char 🤔?

**Comment by mintty** [comment]
U+300C LEFT CORNER BRACKET is a Unicode wide (not ambiguous-width) character. It should be centered within 2 character cells by the font already. I had noticed before that some wide characters have this unpleasant effect and I guess it's a font issue.

**Comment by mintty** [comment]
It could be a combined effect with the Windows font fallback mechanism, i.e. the character may not be included in the selected font and then taken from another font.
Mintty has a mechanism already to _expand_ a character glyph to the required character cell width, however it must be used with care, in order to avoid expanding wide glyphs again as once occurred (#570). An experimental workaround patch to include the two corner brackets in this mechanism works fine but we'll need to find a sustainable criteria which characters to cover by this expansion.
![corner-brackets-expanded](https://user-images.githubusercontent.com/12740416/37863142-6ca739ea-2f59-11e8-96a2-8e3339bdc556.png)

**Comment by mintty** [comment]
Actually, the Windows function to determine the glyph width does not seem to work in the font fallback case, so for a reliable workaround, we would need to measure the real rendered glyph width. This mechanism is also already available in mintty for some special situations (now applied to ambiguous-width characters, using a cache to tame the performance penalty).

**Comment by mintty** [comment]
With the current version, matching CJK brackets are expanded if both are too narrow.
(Alternatively, it could be considered to right-align the left bracket.)

**Comment by mintty** [comment]
Released 2.8.5.
