### ISSUE TITLE
ctrl+tab Z-Order issue

### ISSUE THREAD

**Issue by lededev** [mintty/mintty#773]
When there are some programs start after mintty term windows, press ctrl+tab change mintty term windows, the term window which lost focus will also lost top z-order, and may go to the bottom of the other program's window。

**Comment by mintty** [comment]
Windows Z-order control is a delicate issue. See #652 which used to be fixed and may be a duplicate issue.
Not sure whether it's possible to fix the observed behaviour. Anyway, a precise reproducible test case would help to evaluate whether my observation is the same as yours...

**Comment by mintty** [comment]
By experimenting with the calls in function win_switch (winmain.c), you can achieve that the current window is second-top in z-order after the switch, but then it will be topmost again after the next Ctrl+TAB, which is not desired by the cyclic switching function.
Maybe someone finds another neat permuation of calls there to do the trick.
Otherwise, tabs management infrastructure (win_gotab) which is now available may provide a better solution if reused for Ctrl+TAB.

**Comment by lededev** [comment]
Test build c409140 mintty for msys2, Z-order correct. Thank you!
And I find ctrl+tab press speed must be slower, or I will lost key press。
Is it possible to make it more sensitive?

**Comment by mintty** [comment]
How do you mean "press speed"; what do you lose?
There is no time delay; only the time delta is considered for conditional selection suppression.

**Comment by lededev** [comment]
If I press ctrl+tab 3 times in 1 second, only 1 mintty switch performed.

**Comment by mintty** [comment]
Cannot reproduce. I can quickly switch through multiple windows.

**Comment by mintty** [comment]
Maybe you are testing on a slow system and the actual activation of the window you switch to is delayed, so another click would still go into the old window? Can you visually control that? Does the same thing happen with the previous release version?

**Comment by nobk** [comment]
After windows reboot it disappear. 
Maybe it effect by some program  like online game anti-hack module, I do not know.

**Comment by mintty** [comment]
Released 2.9.0.
