### ISSUE TITLE
Auto conversion from Windows Paths style to Mintty Path style as we paste something 

### ISSUE THREAD

**Issue by ebundy** [mintty/mintty#785]
Replacing manually characters or using a third app to convert the path style is really annoying as you have to do that  dozen times a day. It really decreases the overall experience to use Mintty.   

The idea would be that Mintty provides an option to replace automatically any `c:\foo\bar` by   the Mintty way : `/X/foo/bar` at each time we paste something in the Mintty console.

**Comment by avih** [comment]
Mintty does not have a "way", it only passes the text to the program which runs inside it - which is usually `bash` - which is not part of mintty.

The issue is that bash (and all posix shells) treat backslashes differently than `cmd.exe` does, however, most of the time, just quoting the string is enough, either with single quotes or double quotes, e.g. `dir "C:\Windows" ` or `dir 'C:\Windows'`.

With `cmd.exe` (the windows prompt / interactive shell) you also sometimes need quotes, e.g. when the path contains spaces.

If you want to run `cmd.exe` instead of bash, you can run `cmd` from within bash and now you'll have the normal windows shell inside mintty, and now pasting paths will work even with backslashes and without quotes (but you'll still need quotes if it has spaces). To exit `cmd.exe` prompt back to bash, run the command `exit`.

**Comment by avih** [comment]
The point is that the program which doesn't treat backslash the way you want it to - `bash` is not part of mintty, therefore it's outside the control of mintty and not a mintty issue.

**Comment by mintty** [comment]
If you drag-and-drop a Windows path name (e.g. from Explorer) into mintty, it is in fact converted into POSIX path syntax. If that's not your situation, describe your use case, *precisely*. How do get a backslash into mintty in the first place?

**Comment by ebundy** [comment]
> As a side note, it should have been possible to run winpty cmd and get normal prompt with history etc working, but due to other issues this is not possible at this time, but might be in the future (it's an MSYS2 issue, also unrelated to mintty).
> 
> Usually you use mintty because you want to use the bash shell rather than the windows cmd.exe shell, because bash is considered by some to be better.
> 

And this is the case : I want to use mintty to benefit from the shell commands and because I prefer bash.   So Using mintty as only a cmd/Dos wrapper doesn't have really interest for me. 
As I run cmd from mintty I saw that I still could use some bash commands such as `grep` or `ls` but I noticed also that it produces inconsistent results... as you warned.

> If you drag-and-drop a Windows path name (e.g. from Explorer) into mintty, it is in fact converted into POSIX path syntax. If that's not your situation, describe your use case, precisely. How do get a backslash into mintty in the first place?

Indeed with drag and drop, it is working. Thanks for the advise.
Now using the mouse to drag and drop may be helpful but it doesn't cover all needs : I don't need only to copy paths from a file explorer or assimilated. 
If mintty does some conversion in the drag and drop mode, it sounds that converting the path when we paste something in (finally just a different source of input) makes sense.

**Comment by ebundy** [comment]
As I drag and drop a file path in a vi editor displayed on mintty, I could argue the same thing : why does it change the content ? The drag and drop of of the path may for example the path location of a configu file that I want to keep exactly the same.  
I think that in both cases (drag and drop and copy-paste), we should have an option in the preferences to decide if a path conversion should occur.    
And my original idea was an option in the tool to set that, not forcing this change.    
No I will not stress on any longer. 
Thanks for you feedback.

**Comment by mintty** [comment]
This is now the reverse of your initial request, as I understand.
Please check out option `DropCommands`, it may accomplish already what you want.
