### ISSUE TITLE
No apparent way to increase Font Size with forced font option via shortcut

### ISSUE THREAD

**Issue by Ratione** [mintty/mintty#802]
I am launching mintty through a shortcut that looks like this, currently:

%LOCALAPPDATA%\wsltty\bin\mintty.exe -o Font="SauceCodePro NF" --WSL= --configdir="%APPDATA%\wsltty" -~

Reason for that being no simple solution to getting mintty to recognize the NF fonts, that I have found. 
The problem is, When launched this way, there doesn't seem to be a way to change the font SIZE independent of changing the Font itself. 

When one goes into the the options menu, and attempts to change the font size, it applys the selected font from that menu aswell. As we have established, the NF Fonts do not play nicely with Mintty. As of now, I have been unable to find a way to change the font size via a launch option, or get mintty to recognize NF without tinkering with TTF files, which I am not willing to do.

**Comment by mintty** [comment]
Read the manual. It helps.
-o FontSize or --fs will do.

"Fonts do not play nicely with Mintty" - in general, problem descriptions will help more to get issues resolved than obscure impressions. But I assume you mean it does not appear in the font menu.
The reason is that the mintty font menu only lists monospace fonts, or rather those that are recognized as monospace. Some fonts from amateur sources do not properly contain the respective flag in the font file which should be reported to them as a bug.
