### ISSUE TITLE
Where can I download MinTTY.exe for the latest release?

### ISSUE THREAD

**Issue by naXa777** [mintty/mintty#812]
Is there some easy way to update MinTTY in Windows? I don't want to build it manually if I can avoid it.

I'm not alone. Here's a relevant Stack Overflow post: https://stackoverflow.com/q/50471172/1429387

**Comment by avih** [comment]
There can't be a generic mintty for windows because it's tied very tightly to the underlying unix emulation, and would require a different binary file for cygwin/msys2 and possibly git for windows.

Mintty doesn't work without this unix emulation, so you must get a new version which matches the system you use.  cygwin or msys2 usually update mintty very quickly - so just update with their updater, or build it yourself. And for git-for-windows you'll have to wait for their next release.

**Comment by Biswa96** [comment]
@mintty I've posted [an answer](https://stackoverflow.com/a/52856793/8928481).

**Comment by mintty** [comment]
Thanks.
