### ISSUE TITLE
Right Alt+Fn shortcuts no longer works

### ISSUE THREAD

**Issue by GongT** [mintty/mintty#813]
When I upgrade mintty to newest version (using cygwin setup.exe)    
Right Alt cannot trigger shortcuts anymore, but type some character into terminal.     
Left Alt still works as before

**Comment by mintty** [comment]
Probably related to either of theses 2.9.1 changes:
  * Keyboard AltGr workaround for buggy TeamViewer.
  * Guarding Alt handling from AltGr detection (#790).

Both were important fixes and cannot simply be reverted, but maybe Fn and perhaps keypad keys can be handled as a special case.

**Comment by GongT** [comment]
After some google, I found that the current behavior is right.

Maybe add an `AltGr + Fn` hotkeys. (Or make all hotkeys configurable 💯)

**Comment by GongT** [comment]
Make a note for people never use the function of AltGr.

This small program can remap right alt to the left one: https://github.com/randyrants/sharpkeys

**Comment by mintty** [comment]
> After some google, I found that the current behavior is right.

As right-Alt is supposed to be AltGr on keyboards that do not have a labelled AltGr key, right.

> Maybe add an AltGr + Fn hotkeys. (Or make all hotkeys configurable 💯)

Fn and other hotkeys are in fact configurable since 2.9.1, however, AltGr is not a supported modifier; to be considered.

> Make a note for people never use the function of AltGr.

Considering that AltGr is an important modifier on international keyboards, I don't think it's a good idea to propagate such an approach. Thanks for the hint anyway.
