### ISSUE TITLE
Unable to pipe more command using git bash

### ISSUE THREAD

**Issue by WSLUser** [mintty/mintty#895]
I have a file I’d like to read through with all the goodness Linux provides such as sort, sort -u, more, grep, etc. Attempting to use the `more` command with pure mintty:
`$ cat somefile.csv | more`
` bash: more: command not found`

As I’m used to doing this on Linux, having the ability to do this would be helpful.

This was attempted on a Win7 VM with mintty installed but not cygwin via git bash.

**Comment by Biswa96** [comment]
Type `which more`, the answer should be `/usr/bin/more`. If not then there may be some issue in `$PATH`. Or try to use `/bin/bash.exe --login -i`, you-know-why :)

**Comment by WSLUser** [comment]
It appears git bash doesn’t include `/usr/bin/more`. Which makes no sense. I should be able to get the binary and throw it in there though.

**Comment by mintty** [comment]
Mintty is not the environment that provides your commands.
You are not even clear about the environment you use (Linux, git bash?), either way, it's not a mintty issue.

**Comment by WSLUser** [comment]
I was filing this issue because in git bash, the mintty provided does not have /usr/bin/more. If this is different with the cygwin installation, then they need to update but if it doesn’t, then this is a request for the binary to be ported.

**Comment by mintty** [comment]
> this is a request for the binary to be ported

Maybe. But it is not a request to mintty. Please make yourself familiar with the work split between terminal, shell, etc, e.g.
https://unix.stackexchange.com/questions/4126/what-is-the-exact-difference-between-a-terminal-a-shell-a-tty-and-a-con

**Comment by BrianInglis** [comment]
The standard default pager these days is usually "less" rather than "more" which is installed by default under Linux. The version of more supplied by Windows is available as /proc/cygdrive/c/Windows/System32/more.com so you could define a symlink "ln -s /proc/cygdrive/c/Windows/System32/more.com /usr/bin/more" or "alias more=/proc/cygdrive/c/Windows/System32/more.com". 
Under Cygwin, "more" is available in the optional package util-linux, which is standard under Linux https://packages.debian.org/buster/amd64/util-linux/filelist
