### ISSUE TITLE
shift-enter handling

### ISSUE THREAD

**Issue by scandum** [mintty/mintty#931]
Shift-enter has become the universal way to send a soft enter and I'd like to utilize it for that purpose. I've googled but haven't found anything.

Is there a way to handle shift-enter on mintty/xterm?

**Comment by mintty** [comment]
You could use modifyOtherKeys mode, as compatible with xterm, enabled by an escape sequence.
But that would give you escape sequences for all kinds of modified keys, not only Enter, which your application would need to handle.
Or you can configure a user-defined key assignment:
`KeyFunctions=S+Enter:"enter"`
Instead of the test string "enter", you could specify ^M for a plain CR character, a number to enter an escape sequence, or some command output (see manual). Which character do you actually want?

**Comment by scandum** [comment]
What is the escape code for ModifyOtherKeys? I've looked at the xterm documentation but it doesn't seem to mention how.

As for user-defined, I think sending \e\n would be the most convenient as alt-enter is already tied up in most terminals and that way there is an easily available make-shift alternative, pun intended.

Is it possible to set a user-defined key using escape codes?

**Comment by mintty** [comment]
Escape sequences are described in [ctlseqs.txt](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html).
A literal escape would work inside a string, but a newline would currently be a problem.

**Comment by scandum** [comment]
Thanks, I had another look at the xterm documentation and managed to figure it out.
