### ISSUE TITLE
Can not choose font weight Semibold

### ISSUE THREAD

**Issue by nobk** [mintty/mintty#962]
Environment: Install font sarasa-gothic-ttc-0.10.2.7z from https://github.com/be5invis/Sarasa-Gothic/releases
Install only sarasa-semibold.ttc sarasa-semibolditalic.ttc sarasa-bold.ttc sarasa-bolditalic.ttc

In Mintty settings font chooser, select Sarasa Mono T CL, Semibold, and save. Every time it always display Bold font weight instead of Semibold.
I find Conemu can display Semibold correctly.

**Comment by mintty** [comment]
This is not a good test case as Semibold and Bold are hardly distinguishable.
A new instance of mintty will again use Semibold, anyway, so that seems to work.
Do you face a similar issue with Extralight vs. Light or Normal, perhaps?
I don't see a problem, honestly. If you think there is one, please demonstrate it clearly.
Also it does not help to quote that some other application supposedly does it better.

**Comment by nobk** [comment]
Sorry, I open a conemu in order to compare the font weight. 
But after select font and save, and restart mintty, this issue still happened.
I can not install regular font weight because I do not need it, If I installed, application like firefox will always use regular font weight as default render font, it is not the result what I want.

**Comment by nobk** [comment]
You are right, another font semibold works well, this font is not a good test case.
